name: 'poc3'

services:
  frontend:
    image: "poc3/frontend:1.0.0"
    build:
      context: "frontend"
    ports:
      - "8080:8080/tcp"
  backend:
    image: "poc3/backend:1.0.0"
    environment:
      LOGGER: 'true'
    build:
      context: "backend"